spring:
  application:
    name: crawler
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.215.44.116:3306/crawler?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true
    username: root
    password: root
#    dbcp2:
#      test-while-idle: true
#      max-wait-millis: 30000
#      validation-query: 'SELECT 1'
#      time-between-eviction-runs-millis: 20000
#      min-evictable-idle-time-millis: 28700
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate.id.new_generator_mappings: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
#      hibernate.cache.use_minimal_puts: true
#      hibernate.cache.hazelcast.use_lite_member: true
server:
  port: 8080
  context-path: /